### ISSUE TITLE
Example workflows do not seem to be the latest workflows currently used in laminas and mezzio

### ISSUE THREAD

**Issue by visto9259** [laminas/automatic-releases#260]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | N/A

#### Summary

The workflows in the example folder that one is supposed to copy to a repository, are not the same as what is currently used in repositories.

#### Current behavior

The example workflows have detailed steps for the release job, and are out of date.

#### Expected behavior

The workflows currently used in laminas/mezzio repos refer to the shared workflow.  The examples should be updated.

`release-on-milestone-closed.yml`:

```yml
name: "Automatic Releases"

on:
  milestone:
    types:
      - "closed"

jobs:
  release:
    uses: laminas/workflow-automatic-releases/.github/workflows/release-on-milestone-closed.yml@1.x
    secrets:
      GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
      GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
      ORGANIZATION_ADMIN_TOKEN: ${{ secrets.ORGANIZATION_ADMIN_TOKEN }}
      SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
```

Do we still need `release-on-milestone-closed-triggering-release-event.yml`?

If not, then the README.md file needs to be update to remove the reference to it.
